# NDK Image Pull Secret for dm-nkp-workload-2
# This sealed secret creates the docker registry credentials for pulling NDK images
# Name: ndk-image-pull-secret (required by NDK Helm chart default)
# Scope: cluster-wide (can be used in any namespace)
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: ndk-image-pull-secret
  namespace: ntnx-system
spec:
  encryptedData:
    .dockerconfigjson: AgAKGPHYver2HpXYoYKCOYFAX4ujUXyeVIyQSjz9S1czvFgEQ8Oi9jPoEOkkMsE0CaS2WvroWEuhKMEBQBYVexUn35Q26Bf1/1NR9ZRF83XM+oLLJN6MWfJ4H5QnajFqDoSabRUlWnfxN3+zKFxd8rQ+vpyoizrf4yYthN8wOrMAnr/Y+198dCGSjVIXIsNx/5nVpnuc65VVp6WwD5u15vbUWxxXMVf1e8ujwLNbJ3SmixhhXNHw70WgQ/U4PRI8GvAsQLqGoG7/muoMa4n/iDptLXvrJxHO2fcVNQHwdnqL8evauDO03EZp+pRxmf+73X5cs1jxB2eosP3Wh3QkcCq+XWgnaBSVCqaboTYt04cXSqcvPZHmMhhBc4Z59Sbb8pKELH890mJml05Le6fdnwBV+XBc+CQleGX7I/uqB0dz8qmtCuTwF/O+ggxHHja1te051CVL8HWj2hIt66MtNSu/P1mtWrYzxqtk1m/3YOZYMAHL2zi1W3vz79rXpFT3mZni8G8TbZ2L1B8PAOOftiiK1GRReIuZkj4XDol6EMksWTenPiI5pzC8NUas+PXdYprlhOJuCvSzOJGE5D309Ft9D6+1Ra0/nRSQ8U2Sf4sF6j3zknl/dSw9cvS9gfeEVf7wKf0mAYqCUyHvR2XqWb8w7B3+B1Sl0IuEyIH8h7KlbbewSHN9Muj42AUabAQCCihRtlNJhtWR/ssCHer/70zvYA+7A1VV/HiWm4WRMC73tbDdgP28uzEW4aqo1AT76geLsdhNJKdLTzy6zdcKBcojsQTrcnxfWSWSAkKJh4jsMKbz2PJG2FRnKUpVRaJcXHHkzXIVGWKBNH4sBN2e7jI4pVpGUwBtBFU3ukVXrC/CeZ4BnVw6dmISW38v9PdhUMSDtz561w66tL5kDVhqJ3OOXRwUDC5URF9PPdAWr37TuxHkf05x85WLebv+4I9ph0uQJ4+5AG19
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    type: kubernetes.io/dockerconfigjson
---
# Namespace for NDK/Nutanix apps
apiVersion: v1
kind: Namespace
metadata:
  name: ntnx-system
  labels:
    app.kubernetes.io/part-of: nutanix
