# ClusterResourceSet to deploy NDK Image Pull Secret to all workload clusters
# This should be applied BEFORE enabling the NDK app
#
# NOTE: The SealedSecret below requires all target clusters to have the same
# sealed-secrets controller private key.
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ndk-image-pull-secret-resources
  namespace: dm-dev-workspace
  labels:
    app.kubernetes.io/part-of: ndk
    app.kubernetes.io/component: cluster-resource-set
data:
  # Namespace for NDK/Nutanix applications
  namespace.yaml: |
    apiVersion: v1
    kind: Namespace
    metadata:
      name: ntnx-system
      labels:
        app.kubernetes.io/part-of: nutanix

  # SealedSecret for NDK image registry credentials
  # This sealed secret uses cluster-wide scope so it can be used from any namespace
  sealed-secret.yaml: |
    apiVersion: bitnami.com/v1alpha1
    kind: SealedSecret
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      name: ndk-image-pull-secret
      namespace: ntnx-system
    spec:
      encryptedData:
        .dockerconfigjson: AgBaNhNo0iep4pFP98S9YGjqXgeGTMHEBEwSp9kf+NLkTjtKjniqWNarFAZujd3G+QOQLI53fk/xAwsYrlnQxirNCR+dFDidRcqh+//Rikw2OosRwvnHc5JNrwo3xwErqyoDkykY/kk0I9plnouQBQkcsH4ikguIxjENOxTzRsvMHlvUBp7SovoMzPd2kRxyqoA5NQ1isrC4zqhBByVp3O6POAXzlMCbqg6qDs8HmcDYkE0gRCe+cDtL+BoO7zjh0Wjc03Y4o9zF4UDcko4xeL4MTw94+DKITkG70E+dSuq1s/WNgg08P4zbYzjLyPDnrEtLf/RNLp/tERlKd6GRvlLX1e2s2A7zfVKeeCmxdCj6GCMYfxKgV4p/Tms/Tbn10T4NTqi2D0qWc81ZO9X4HzLT3MrH5fo3Wv/D47xGpo8GHukwYaQhMBbs1JYEbrxFlnGRoVgn8bG5PFOms+k0T9O2E615ywSFncFem8+ZWQZjONsV7Jfh6qU/kmHAQTuTkU9ioltZwXD41p7MzP91yVeJbskOnJQrScsrzkmOMyLx3wIwte6H8Gam0mgpqj2VlPLFqoEU9ry0ztpQ70Kd7epvKkMa1neLflbpJ9mKSvz++cwupqjzWZwDfyFyQgRMKuY31Qi5US/zd9eDX6Ue+p3D2Olsmd7PTZ2DqtAvBIxgcY9uidw3YcDwpbZt0mLzONsjATplXzTI2U1CWfFILSgkE4ac4EQ/+F7AbQPcphtkJ3f2KNvB4zBupC6wTt+Lq2N8wpJyrl78JIRyj3tAqXvYbxvAtH+JHwI2kPRT9MjNB4k4Eh/suS4YFBdLOjGU8JprrP9oNLdeuTzSxH3NANa7gBChV4eI+bS3OtmoIJsSLAGPJDh1CfAAGHnYPVnBho2mHJTYY/jaqVmssa6cAb+DOwEihq8VK8ITcGS9okPMBs1mpybtaAb/mDjNoR72Mg==
      template:
        metadata:
          annotations:
            sealedsecrets.bitnami.com/cluster-wide: "true"
          name: ndk-image-pull-secret
          namespace: ntnx-system
        type: kubernetes.io/dockerconfigjson
---
apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: ndk-image-pull-secret-crs
  namespace: dm-dev-workspace
  labels:
    app.kubernetes.io/part-of: ndk
    app.kubernetes.io/component: cluster-resource-set
spec:
  # Select all Nutanix-based clusters in this namespace
  clusterSelector:
    matchLabels:
      konvoy.d2iq.io/provider: nutanix
  # Resources to deploy to matching clusters
  resources:
    - kind: ConfigMap
      name: ndk-image-pull-secret-resources
  # ApplyOnce means resources are applied once when cluster matches
  strategy: ApplyOnce
